name: CD

on:
  release:
    types:
      - published

jobs:
  cd:
    uses: halo-sigs/reusable-workflows/.github/workflows/plugin-cd.yaml@main
    secrets: inherit
    permissions:
      contents: write
    with:
      app-id: app-Qxhpp
