name: CD

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  cd:
    uses: JohnNiang/reusable-workflows/.github/workflows/plugin-cd.yaml@main
    secrets: inherit
    permissions:
      contents: write
